/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#faf8ff",
        surface: "#faf8ff",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "on-surface": "#131b2e",
        "on-surface-variant": "#424754",
        outline: "#727785",
        "outline-variant": "#c2c6d6",
        primary: "#0058be",
        "primary-container": "#2170e4",
        "on-primary": "#ffffff",
        "on-primary-container": "#fefcff",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc6ff",
        "primary-light": "#2170e4",
        "primary-dark": "#004395",
        secondary: "#4b41e1",
        "secondary-container": "#645efb",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#e2dfff",
        tertiary: "#6b38d4",
        "tertiary-container": "#8455ef",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#e9ddff",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        match: "#059669",
        "match-soft": "rgba(16, 185, 129, 0.12)",
        warning: "#d97706",
        "warning-soft": "rgba(245, 158, 11, 0.12)",
        console: "#131b2e",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        mono: ["ui-monospace", "SFMono-Regular", "monospace"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
      },
      boxShadow: {
        institutional: "0 1px 3px 0 rgba(15, 23, 42, 0.04), 0 1px 2px -1px rgba(15, 23, 42, 0.02)",
        "institutional-lg": "0 10px 15px -3px rgba(15, 23, 42, 0.06), 0 4px 6px -4px rgba(15, 23, 42, 0.03)",
        glow: "0 0 12px 0 rgba(139, 92, 246, 0.15)",
      },
      spacing: {
        "gutter-desktop": "1.5rem",
        "sidebar-width-expanded": "18rem",
        "copilot-drawer-width": "24rem",
      },
      maxWidth: {
        content: "1440px",
      },
    },
  },
  plugins: [],
};
